name: k6 Performance Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  k6_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # --- PASOS CLAVE PARA LA TAREA ---
    
    - name: Start Node App
      run: npm start &
      
    - name: Wait for App
      run: sleep 10

    - name: Run k6 Load Test
      uses: grafana/k6-action@v0.3.0
      env:
        K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      with:
        filename: script_k6.js
        flags: --out cloud
